site_name: ZhaoCake's Blog
site_url: https://zhaocake.github.io/
repo_url: https://github.com/ZhaoCake/zhaocake.github.io
repo_name: ZhaoCake/zhaocake.github.io

plugins:
  - search
  - blog

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji

#nav:
#  - Home: index.md
#- Blog:
#    - blog/index.md

theme:
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  logo: assert/zhao.png
  favicon: assert/zhao.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to auto mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhaoCake
    - icon: fontawesome/brands/qq
      link: tencent://message/?uin=2317634877&Site=&Menu=yes
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1711392619
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/42-48-12-1

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

copyright: Copyright &copy; 2024 Cake Zhao
